import {
  Armchair,
  BarChart3,
  Ban,
  BookOpen,
  Building2,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  CircleDot,
  CircleX,
  Clock3,
  CreditCard,
  Download,
  Eye,
  FileText,
  Landmark,
  Hand,
  KeyRound,
  LoaderCircle,
  Lock,
  MapPin,
  CirclePlus,
  PauseCircle,
  Pencil,
  Plus,
  RefreshCw,
  Save,
  Settings,
  Star,
  Trash2,
  TriangleAlert,
  Undo2,
  UserRound,
  UsersRound,
  X,
  Zap,
} from 'lucide-react';

const icons = {
  bookings: BookOpen,
  building: Building2,
  calendar: CalendarDays,
  camera: Camera,
  chart: BarChart3,
  check: Check,
  checkCircle: CheckCircle2,
  clock: Clock3,
  creditCard: CreditCard,
  eye: Eye,
  file: FileText,
  location: MapPin,
  lock: Lock,
  pause: PauseCircle,
  refresh: RefreshCw,
  reports: BarChart3,
  save: Save,
  status: CircleDot,
  table: Armchair,
  trash: Trash2,
  user: UserRound,
  users: UsersRound,
  venue: Landmark,
  close: X,
  hand: Hand,
  key: KeyRound,
  money: CreditCard,
  plus: CirclePlus,
  add: Plus,
  alert: TriangleAlert,
  ban: Ban,
  cancel: CircleX,
  download: Download,
  edit: Pencil,
  loading: LoaderCircle,
  settings: Settings,
  star: Star,
  undo: Undo2,
  zap: Zap,
};

export default function AppIcon({ name, size = 18, className, ...props }) {
  const Icon = icons[name] || FileText;
  return <Icon aria-hidden="true" className={className} size={size} {...props} />;
}
